### ISSUE TITLE
displayed incorrect charset 

### ISSUE THREAD

**Issue by danzhang-pm** [AdobeDocs/experience-manager-cloud-service.zh-Hans#1]
Issue in ./help/sites-cloud/authoring/fundamentals/editing-content.md

When selecting simplified Chinese, the page is partially displayed in traditional Chinese (2nd half of the page).
Pages under the same root path have similar issue.

**Comment by lio47708** [comment]
Thank you. We are looking into this issue.

**Comment by lio47708** [comment]
@danzhang-pm Thank you for your feedback. Please provide a few screenshots so that we may more quickly fix the issue. On our end this issue is not clearly showing as the description on the same page.

**Comment by danzhang-pm** [comment]
It seems magically working well now. I have a screenshot captured yesterday. but as it's not reproducible, maybe we could close this ticket. I will re-open if I see the problem again. Thanks!

**Comment by lio47708** [comment]
You are welcome. Please note that this issue should now be resolved.
